# Generated by Django 6.0 on 2025-12-31 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
