# Generated by Django 6.0 on 2025-12-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["title"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["title"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.RemoveField(
            model_name="course",
            name="name",
        ),
        migrations.RemoveField(
            model_name="course",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="name",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="video_url",
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение курса",
                null=True,
                upload_to="uploads/",
                verbose_name="изображение",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="title",
            field=models.CharField(
                default="Без названия",
                help_text="Введите название курса",
                max_length=250,
                verbose_name="наименование",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение курса",
                null=True,
                upload_to="uploads/",
                verbose_name="изображение",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="title",
            field=models.CharField(
                default="",
                help_text="Введите название урока",
                max_length=250,
                verbose_name="наименование",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video",
            field=models.CharField(
                blank=True,
                help_text="Введите ссылку на видео курса",
                null=True,
                verbose_name="ссылка на видео",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание курса",
                null=True,
                verbose_name="описание",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course",
                to="lms.course",
                verbose_name="курс",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание курса",
                null=True,
                verbose_name="описание",
            ),
        ),
    ]
