# Generated by Django 6.0 on 2025-12-28 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_alter_course_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
        migrations.RemoveField(
            model_name="course",
            name="image",
        ),
        migrations.RemoveField(
            model_name="course",
            name="title",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="image",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="title",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="video",
        ),
        migrations.AddField(
            model_name="course",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Введите название курса",
                max_length=50,
                null=True,
                verbose_name="Название курса",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="lms/preview_course"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Введите название урока",
                max_length=50,
                null=True,
                verbose_name="Название урока",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="lms/preview_lesson"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.CharField(
                blank=True,
                help_text="Введите ссылку на видеоурок",
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Введите описание курса",
                max_length=50,
                null=True,
                verbose_name="Описание курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                help_text="Выберите курс",
                on_delete=django.db.models.deletion.CASCADE,
                to="lms.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Введите описание урока",
                max_length=50,
                null=True,
                verbose_name="Описание урока",
            ),
        ),
    ]
